set(LINKER_FILE_PATH ${CMAKE_SOURCE_DIR}/example.lsl)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_C_COMPILER "${TOOLSET_PATH}/ctc/bin/cctc.exe" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "${TOOLSET_PATH}/ctc/bin/ctc.exe" CACHE FILEPATH "")
set(CMAKE_ASM_COMPILER "${TOOLSET_PATH}/ctc/bin/astc.exe" CACHE FILEPATH "")
set(CMAKE_LINKER "${TOOLSET_PATH}/ctc/bin/ltc.exe" CACHE FILEPATH "")
set(CMAKE_AR "${TOOLSET_PATH}/ctc/bin/artc.exe" CACHE FILEPATH "")

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR  "TriCore")
set(CMAKE_TASKING_TOOLSET   "TriCore v6.3r1")
set(CMAKE_CROSSCOMPILING 1)

set(CMAKE_C_FLAGS   "-Ctc1766 -v -g3 -O0 ")

set(CMAKE_CXX_FLAGS "-Ctc1766 -v -g3 -O0 ")

set(CMAKE_ASM_FLAGS "-Ctc1766 -ga -c -ig --emit-locals -OGS -tc")


set(CMAKE_C_LINK_FLAGS "-d\"${LINKER_FILE_PATH}\" -O0 -M -lfp_fpu -lrt -lc")
set(CMAKE_C_LINK_EXECUTABLE "\"${CMAKE_LINKER}\" -o <TARGET> <OBJECTS> <LINK_LIBRARIES> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS>")

set(CMAKE_FIND_ROOT_PATH  "${CMAKE_SOURCE_DIR}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)